receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:

  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  otlphttp/launchdarkly:
    traces_endpoint: https://events-stg.launchdarkly.com/otlp/traces
    encoding: json
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN}
      X-LaunchDarkly-Project: toggle-airlines
      X-LaunchDarkly-Environment: henry-dev

processors:
  groupbytrace:
    wait_duration: 3s

  filter/launchdarkly-spanevents:
    error_mode: ignore
    traces:
      spanevent:
        - 'not (name == "feature_flag" or name == "exception")'

  filter/launchdarkly-spans:
    error_mode: ignore
    traces:
      span:
        - 'not (attributes["http.route"] != nil or Len(events) > 0)'

  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces/ld:
      receivers: [otlp]
      processors:
        [
          filter/launchdarkly-spanevents,
          filter/launchdarkly-spans,
          groupbytrace,
          batch,
        ]
      exporters: [logging, otlphttp/launchdarkly, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
