receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:

  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  otlphttp/launchdarkly:
    traces_endpoint: https://events.launchdarkly.com/otlp/traces
    encoding: json
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN}
      X-LaunchDarkly-Project: toggle-airlines
      X-LaunchDarkly-Environment: henry-dev

  otlphttp/pipedream:
    traces_endpoint: https://a628ef498514fa900ecde53de35bd062.m.pipedream.net
    encoding: json
    compression: none
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN}
      X-LaunchDarkly-Project: toggle-airlines
      X-LaunchDarkly-Environment: henry-dev

processors:
  groupbytrace:
    wait_duration: 5s

  filter/launchdarkly-spanevents:
    error_mode: ignore
    traces:
      spanevent:
        - 'not (name == "feature_flag" or name == "exception")'

  filter/launchdarkly:
    error_mode: ignore
    traces:
      span:
        - 'not (attributes["http.route"] != nil or Len(events) > 0)'

  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces/ld:
      receivers: [otlp]
      processors: [filter/launchdarkly, groupbytrace, batch]
      exporters:
        [logging, otlphttp/launchdarkly, otlp/jaeger, otlphttp/pipedream]
    # traces/jaeger:
    #   receivers: [otlp]
    #   processors: [filter/launchdarkly, batch]
    #   exporters: [logging, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
