receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  otlp/honeycomb:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: ${env:HONEYCOMB_API_KEY}

  otlphttp/launchdarkly:
    traces_endpoint: https://events-stg.launchdarkly.com/otlp/traces
    encoding: json
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN_STAGING}
      X-LaunchDarkly-Project: otlp-blitz
      X-LaunchDarkly-Environment: henry-dev

processors:
  groupbytrace:
    wait_duration: 3s

  # Remove all span events that are not "feature_flag" or "exception"
  filter/launchdarkly-spanevents:
    error_mode: ignore
    traces:
      spanevent:
        - 'not (name == "feature_flag" or name == "exception")'

  # Remove all spans that do not have an HTTP route or any span events left after the previous filter
  filter/launchdarkly-spans:
    error_mode: ignore
    traces:
      span:
        - 'not (attributes["http.route"] != nil or Len(events) > 0)'

  batch:

extensions:
  health_check:

service:
  pipelines:
    # Add a new pipeline to send data to LaunchDarkly
    traces/ld:
      receivers: [otlp]
      processors:
        [
          filter/launchdarkly-spanevents,
          filter/launchdarkly-spans,
          groupbytrace,
          batch,
        ]
      exporters: [logging, otlphttp/launchdarkly, otlp/jaeger]
    traces/honeycomb:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/honeycomb]
