receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:

  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  otlphttp/launchdarkly:
    traces_endpoint: https://events.launchdarkly.com/otlp/traces
    encoding: json
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN}
      X-LaunchDarkly-Project: toggle-airlines
      X-LaunchDarkly-Environment: henry-dev

  otlphttp/pipedream:
    traces_endpoint: https://a628ef498514fa900ecde53de35bd062.m.pipedream.net
    encoding: json
    compression: none
    headers:
      Authorization: ${env:LD_ACCESS_TOKEN}
      X-LaunchDarkly-Project: toggle-airlines
      X-LaunchDarkly-Environment: henry-dev

processors:
  groupbytrace:

  batch:
    timeout: 5s

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [groupbytrace, batch]
      exporters:
        [logging, otlp/jaeger, otlphttp/launchdarkly, otlphttp/pipedream]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
